org: mitchel
app: aws-flask-ltbxd
service: aws-flask-ltbxd

frameworkVersion: "3"

custom:
  wsgi:
    app: app.app

package:
  exclude:
    - node_modules/**

provider:
  name: aws
  runtime: python3.9
  region: eu-west-1

functions:
  api:
    handler: app.ScrapeLetterboxdFavourites
    events:
      - http:
          path: /ScrapeLetterboxdFavourites
          method: GET
          cors: true

plugins:
  - serverless-wsgi
  - serverless-python-requirements
